stages:
- name: Build & Push
  steps:
    - runScriptConfig:
        image: java:8
        shellScript: ./mvnw clean install -Pdocker
- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./deployment.yaml