stages:
- name: Build & Push
  steps:
    - runScriptConfig:
        image: java:8
        shellScript: ./mvnw clean install
- name: Publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
        tag: spring-boot-demo:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./deployment.yaml