kind: Service
apiVersion: v1
metadata:
  name: spring-boot-demo-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: spring-boot-demo
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-demo
  namespace: ${NAMESPACE}
  labels:
    app: spring-boot-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-demo
  template:
    metadata:
      labels:
        app: spring-boot-demo
    spec:
      imagePullSecrets:
      - name: nexus3
      containers:
      - name: spring-boot-demo
        image: nexus3.memnon.se:8443/spring-boot-demo:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: APP_NAME
            value: spring-boot-demo
          - name: BOOT_ADMIN_ENABLED
            value: "true"
          - name: BOOT_ADMIN_PREFER_IP
            value: "true"
          - name: CONTEXT_PATH
            value: /spring-boot-demo
          - name: BOOT_ADMIN_URL
            valueFrom:
              configMapKeyRef:
                key: bootAdminUrl
                name: common
                optional: false